#!/bin/sh

cross build --target aarch64-unknown-linux-musl --release

ssh -i ~/.ssh/login.pem ec2-user@3.22.67.226 -t "
    rm /home/ec2-user/app/proxy
" &> /dev/null

scp -i ~/.ssh/login.pem target/aarch64-unknown-linux-musl/release/proxy ec2-user@3.22.67.226:/home/ec2-user/app/proxy;

echo launching systemd service...

ssh -i ~/.ssh/login.pem ec2-user@3.22.67.226 -t "
    sudo systemctl stop proxy.service
    sudo journalctl --rotate
    sudo journalctl --vacuum-time=1s
    sudo systemctl start proxy.service
" &> /dev/null

ssh -i ~/.ssh/login.pem ec2-user@3.22.67.226 -t "
    sudo journalctl -fu proxy.service
" 2> /dev/null
